// ---------------------------------------------------------------------------
// new4 Phase 5 — CI gate snippet generator (declarative, no logic — ADR 0025).
//
// Single source of truth for the consumer-facing GitHub Actions workflow that
// gates a repo on its agent-tool surface. A TS constants/template module so it
// bundles into the CLI + calllint-mcp via esbuild (no fs reads at runtime).
//
// Two modes:
//   - "drift"    : fail the PR when the approved capability surface changes
//                  (verify --approved --ci). Requires a committed approved.json.
//   - "scan-all" : report-only visibility (scan-all --no-emoji), never gates.
//
// The published snippet uses `npx -y calllint` so external repos need no install.
// ---------------------------------------------------------------------------

export const CI_GATE_MODES = ["drift", "scan-all"] as const
export type CiGateMode = (typeof CI_GATE_MODES)[number]

export interface CiGateOptions {
  /** "drift" (default) gates on approved-state; "scan-all" is report-only. */
  mode?: CiGateMode
}

/** Path filters that should trigger the gate (agent-tool surfaces). */
export const CI_GATE_PATHS = [
  "**/mcp.json",
  "**/.mcp.json",
  "**/settings.json",
  "**/config.toml",
  ".cursor/**",
  ".vscode/**",
  "claude_desktop_config.json",
  "CLAUDE.md",
  "AGENTS.md",
  ".calllint/approved.json",
] as const

function pathsBlock(): string {
  return CI_GATE_PATHS.map((p) => `      - ${JSON.stringify(p)}`).join("\n")
}

const DRIFT_STEP = `      - name: CallLint drift gate
        shell: bash
        run: |
          if [ -f .calllint/approved.json ]; then
            npx -y calllint verify --approved --ci --no-emoji
          else
            echo "No .calllint/approved.json — seed it with: npx calllint approve"
            echo "Running report-only scan-all (not gating)."
            npx -y calllint scan-all --no-emoji || true
          fi`

const SCAN_ALL_STEP = `      - name: CallLint scan-all (report-only)
        shell: bash
        run: npx -y calllint scan-all --no-emoji || true`

/**
 * Render the consumer-facing `.github/workflows/calllint.yml` text. Static,
 * deterministic. The repo's own committed workflow stays in lockstep with the
 * "drift" output (asserted by a test).
 */
export function renderCiGate(opts: CiGateOptions = {}): string {
  const mode: CiGateMode = opts.mode ?? "drift"
  const step = mode === "scan-all" ? SCAN_ALL_STEP : DRIFT_STEP
  const headline =
    mode === "scan-all"
      ? "CallLint agent-tool surface report (report-only; never gates)."
      : "CallLint agent-tool surface drift gate (fails on approved-state drift)."

  return `# ${headline}
# Generated by \`calllint\` (generate_ci_gate_snippet). CallLint is static and
# NEVER executes a scanned server.
name: calllint

on:
  pull_request:
    paths:
${pathsBlock()}

permissions:
  contents: read

jobs:
  surface-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
${step}
`
}
