/**
 * THE OBSERVER INVARIANT — `scripts/check-official-sources.mjs` can actually SEE both of its
 * subjects, and actually COMPARES them against a baseline.
 *
 * This exists because the script was doubly vacuous, and both halves were green. Measured
 * 2026-08-22:
 *
 *   1. CANDIDATE DISCOVERY FETCHED NOTHING. The URL loop read `manifest.sources` only, so
 *      `manifest.candidateFeeds` was generated by the SSOT projector, constrained by a
 *      published schema, asserted by an invariant on its `role` — and never once opened.
 *      §84's weekly discovery stage had no observation stage at all. The anti-vacuity floor
 *      that should have caught it (`sources.length === 0`) had a denominator that did not
 *      include the thing being missed, which is this repo's dominant fault class stated in
 *      its purest form.
 *
 *   2. CHANGE DETECTION HAD NEVER RUN. `distribution-watch.yml` uploaded the artifact and
 *      nothing ever downloaded it, and the path is untracked — so `previous` was always
 *      null, all 27 URLs reported `NEW`, and every STATUS / BODY / REACHABILITY / REDIRECT
 *      comparison below was dead code, weekly, forever. The workflow's own comment asserted
 *      that uploading "is what makes week-over-week change detection possible." It was not.
 *
 * Both failures were invisible for the same reason: a missing baseline and a quiet week are
 * both spelled "no interesting output". `NEW` on everything reads like a healthy first run.
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────
 * HOW THIS TESTS A SCRIPT WITH HARDCODED REPO PATHS, WITHOUT MUTATING THE REPO
 * ─────────────────────────────────────────────────────────────────────────────────────────
 * The script resolves `repoRoot` from `import.meta.url` and reads/writes fixed relative
 * paths under it. So the negative controls COPY it into a temp tree, where its own
 * `repoRoot` becomes the temp dir: it then reads a synthetic `scripts/distribution-sources.json`
 * and writes a throwaway artifact. Nothing in the real tree is touched, and no production
 * code grew an env-var seam for the benefit of a test. The copy is made from the real path at
 * run time, so it cannot go stale the way a checked-in fixture of the script would.
 *
 * NO EGRESS. Live runs point the synthetic manifest at a loopback `http.createServer` bound
 * to 127.0.0.1 on an ephemeral port — no DNS, no outbound connection, no vendor contact. The
 * generator's `https://` rule does not apply here because the synthetic manifest is written
 * directly, and the observer deliberately fetches whatever URL it is given.
 *
 * WHY A LOOPBACK SERVER RATHER THAN ONLY `--offline`. `--offline` exits before fetching, so it
 * can prove the denominator and both anti-vacuity floors but CANNOT execute one line of the
 * comparison code — which is precisely the half that had never run. A test that stopped at
 * `--offline` would re-create the original defect at the test layer: full coverage of the
 * cheap half, zero coverage of the half that was broken.
 *
 * THE POSITIVE CONTROL IS THE POINT. `a candidate-feed BODY change is detected and tagged`
 * fails if `sourceKind` stops being carried, if the feed stops being fetched, or if the
 * baseline stops being read. That single assertion covers both original vacuities.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest"
import { execFile, execFileSync } from "node:child_process"
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync, symlinkSync } from "node:fs"
import { createServer, type Server } from "node:http"
import { tmpdir } from "node:os"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { promisify } from "node:util"
import type { AddressInfo } from "node:net"

const execFileAsync = promisify(execFile)

const here = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(here, "..", "..")
const REAL_SCRIPT = resolve(ROOT, "scripts", "check-official-sources.mjs")

/** The loopback origin the synthetic manifests point at. Assigned in `beforeAll`. */
let origin = ""
let server: Server
/** Mutated between live runs to simulate a vendor changing their page. */
let served = { host: { status: 200, body: "host-v1" }, feed: { status: 200, body: "feed-v1" } }

/** A temp tree whose root becomes the copied script's `repoRoot`. */
let tmpRoot: string

type Run = { status: number; out: string }

/**
 * Budget for the live sequence's `beforeAll`, which spawns FOUR node child processes in series.
 *
 * WHY THIS IS NOT A FLAKE-SUPPRESSING TIMEOUT BUMP. Measured: the sequence takes ~2.4s when the
 * file runs alone, and vitest's default 10s hook budget is generous against that. But this suite
 * runs inside a 263-file project, and under that concurrency four serial `execFile` spawns —
 * which contend for the SAME cores as every other worker — exceeded 10s and reported
 * `Hook timed out in 10000ms`. The work is not slow or racy; the default budget was set for hooks
 * that do not fork processes at all.
 *
 * A global `hookTimeout` was rejected: it would relax the budget for the other 88 hook call sites
 * in this project, most of which do no I/O and genuinely should fail fast, hiding real hangs
 * elsewhere. The cost of this being wrong is bounded — an actually-hung sequence takes 60s to
 * report instead of 10s, on one file.
 */
const LIVE_SEQUENCE_TIMEOUT_MS = 60_000

/**
 * Run the COPIED script against the temp tree. Never touches the real repo.
 *
 * ASYNC ON PURPOSE. The fixture server runs on THIS process's event loop, so a blocking
 * `execFileSync` cannot serve it: the child's fetch never gets accepted and every URL times
 * out after 15s. Measured — the first draft of this test used `execFileSync` and produced
 * `2 unreachable / timeout after 15000ms`, which is a defect in the test, not in the script.
 */
async function runCopy(args: string[] = []): Promise<Run> {
  const script = join(tmpRoot, "scripts", "check-official-sources.mjs")
  try {
    const { stdout } = await execFileAsync(process.execPath, [script, ...args], {
      encoding: "utf8",
      cwd: tmpRoot,
    })
    return { status: 0, out: stdout }
  } catch (err: unknown) {
    const e = err as { code?: number; stdout?: string; stderr?: string }
    return { status: e.code ?? -1, out: `${e.stdout ?? ""}${e.stderr ?? ""}` }
  }
}

/** Write the synthetic manifest the copied script will read. */
function writeManifest(manifest: unknown): void {
  writeFileSync(join(tmpRoot, "scripts", "distribution-sources.json"), JSON.stringify(manifest, null, 2))
}

const WATCH_LIST_REL = join("artifacts", "distribution", "agent-harness-watch-list.yml")

/**
 * Write the synthetic watch list, or remove it to exercise the absent case.
 *
 * Hand-rolled YAML rather than a serializer: the point is to feed the script the same shape a
 * human commits, and a serializer would let a malformed-entry control silently become
 * well-formed.
 */
function writeWatchList(watches: Array<Record<string, string>> | null): void {
  const abs = join(tmpRoot, WATCH_LIST_REL)
  if (watches === null) {
    rmSync(abs, { force: true })
    return
  }
  mkdirSync(dirname(abs), { recursive: true })
  const body = watches.length === 0
    ? "watches: []\n"
    : `watches:\n${watches.map((w) => Object.entries(w).map(([k, v], i) => `  ${i === 0 ? "- " : "  "}${k}: ${v}`).join("\n")).join("\n")}\n`
  writeFileSync(abs, body)
}

const ARTIFACT_REL = join("artifacts", "distribution-watch", "official-sources.json")
const artifactPath = () => join(tmpRoot, ARTIFACT_REL)
const readArtifact = () => JSON.parse(readFileSync(artifactPath(), "utf8"))

/** One host URL + one candidate-feed URL, both on loopback. The ordinary, well-formed shape. */
function bothKinds() {
  return {
    describes: { release: "test" },
    sources: [{ hostId: "loopback-host", primarySources: [`${origin}/host`], watchFor: ["config path"] }],
    candidateFeeds: [{ feedId: "loopback-feed", primarySources: [`${origin}/feed`], watchFor: ["new client"] }],
  }
}

beforeAll(async () => {
  server = createServer((req, res) => {
    const which = req.url === "/feed" ? served.feed : served.host
    res.writeHead(which.status, { "content-type": "text/plain" })
    res.end(which.body)
  })
  await new Promise<void>((ok, fail) => {
    server.once("error", fail)
    server.listen(0, "127.0.0.1", ok)
  })
  const addr = server.address() as AddressInfo
  origin = `http://127.0.0.1:${addr.port}`

  tmpRoot = mkdtempSync(join(tmpdir(), "official-sources-"))
  mkdirSync(join(tmpRoot, "scripts"), { recursive: true })
  copyFileSync(REAL_SCRIPT, join(tmpRoot, "scripts", "check-official-sources.mjs"))

  /*
   * The copied script imports `yaml` (added 2026-08-24 to read the harness watch list), and a
   * bare temp tree has no `node_modules` — so every run in this file died with
   * ERR_MODULE_NOT_FOUND the moment that import landed. Measured: 9 negative controls failed at
   * once, all of them for a reason unrelated to what they assert.
   *
   * A junction to the real `node_modules` is the fix that keeps the copy behaving like
   * production: same resolution, same package version, no env-var seam added to production code
   * for a test's benefit, and no vendored copy of the parser to go stale. `junction` is the type
   * that works on Windows without elevation; on POSIX it is accepted as a plain dir symlink.
   */
  symlinkSync(join(ROOT, "node_modules"), join(tmpRoot, "node_modules"), "junction")
})

afterAll(async () => {
  await new Promise<void>((ok) => server.close(() => ok()))
  rmSync(tmpRoot, { recursive: true, force: true })
})

describe("the production denominator: the real manifest gives the observer both subjects", () => {
  it("the REAL script, offline, reports at least one candidate feed contributing at least one URL", () => {
    // The assertion that would have failed for the whole period in which candidate discovery
    // observed nothing. `--offline` exits before any fetch AND before the artifact write, so
    // this runs the real script against the real manifest while touching neither network nor
    // tree. Baseline state is deliberately NOT asserted here: the artifact path is untracked,
    // so whether one exists locally is not a fact about the repo.
    const out = execFileSync(process.execPath, [REAL_SCRIPT, "--offline"], { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] })
    const shape = out.match(/Manifest shape verified \((\d+) host source\(s\) → (\d+) URL\(s\), (\d+) candidate feed\(s\) → (\d+) URL\(s\)\)/)
    expect(shape, `the offline shape line is missing — got:\n${out}`).not.toBeNull()
    const [, hosts, hostUrls, feeds, feedUrls] = shape!.map(Number) as unknown as number[]
    expect(hosts, "zero host sources means the observer sees nothing").toBeGreaterThan(0)
    expect(hostUrls).toBeGreaterThan(0)
    expect(feeds, "the SSOT declares candidate feeds; a 0 here means the observer stopped reading them").toBeGreaterThan(0)
    expect(feedUrls, "candidate discovery would fetch nothing while the job still exited 0").toBeGreaterThan(0)
  })

  it("the REAL watch list contributes at least one release-feed URL", () => {
    // Same denominator argument as the candidate half above, applied to the third kind. The
    // watch list is committed, so unlike the untracked artifact its contents ARE a fact about
    // the repo and can be asserted here.
    const out = execFileSync(process.execPath, [REAL_SCRIPT, "--offline"], { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] })
    const shape = out.match(/watch list (\d+) entr\(ies\) → (\d+) URL\(s\)/)
    expect(shape, `the watch-list shape line is missing — got:\n${out}`).not.toBeNull()
    const [, entries, urls] = shape!.map(Number) as unknown as number[]
    expect(entries, "the committed watch list declares harnesses; a 0 means the observer stopped reading it").toBeGreaterThan(0)
    expect(urls, "release-feed observation would fetch nothing while the job still exited 0").toBeGreaterThan(0)
  })

  it("every committed watch entry names a harness the discovery layer actually supports", () => {
    // A watch target for a harness CallLint cannot extract is a page nobody can act on. This
    // ties the list to `AgentType` so the two cannot drift apart silently.
    const yml = readFileSync(resolve(ROOT, WATCH_LIST_REL), "utf8")
    const names = [...yml.matchAll(/^\s*-\s+name:\s*(\S+)/gm)].map((m) => m[1])
    expect(names.length, "no watch entries parsed out of the committed list").toBeGreaterThan(0)

    const agentTypes = readFileSync(resolve(ROOT, "packages", "discovery", "src", "types.ts"), "utf8")
    const declared = new Set([...agentTypes.matchAll(/^\s*\|\s*"([a-z0-9-]+)"/gm)].map((m) => m[1]))
    expect(declared.size, "AgentType union did not parse — the assertion below would be vacuous").toBeGreaterThan(0)

    const unknown = names.filter((n) => !declared.has(n))
    expect(unknown, `watch entries name harnesses absent from AgentType: ${unknown.join(", ")}`).toEqual([])
  })

  it("every github-releases entry carries the repo it claims, so a silent rename is checkable", () => {
    // The GitHub API follows renames, so a stale `owner/name` keeps returning 200 and reads as
    // healthy. Four of twelve entries were wrong this way when the list was first written. The
    // `repo:` field is what makes the claim verifiable against the API rather than by eye.
    const yml = readFileSync(resolve(ROOT, WATCH_LIST_REL), "utf8")
    const blocks = yml.split(/^\s*-\s+name:/m).slice(1)
    expect(blocks.length, "no watch entries parsed — the loop below would assert nothing").toBeGreaterThan(0)

    const missing = blocks
      .filter((b) => /kind:\s*github-releases/.test(b) && !/repo:\s*[\w.-]+\/[\w.-]+/.test(b))
      .map((b) => b.trim().split(/\s/)[0])
    expect(missing, `github-releases entries without a parseable \`repo:\`: ${missing.join(", ")}`).toEqual([])
  })
})

describe("anti-vacuity floors, each with its own denominator", () => {
  it("NC-A: a feed declared with zero URLs FAILS — discovery would observe nothing", async () => {
    writeManifest({
      sources: [{ hostId: "h", primarySources: [`${origin}/host`] }],
      candidateFeeds: [{ feedId: "f", primarySources: [] }],
    })
    const run = await runCopy(["--offline"])
    expect(run.status, "a feed that contributes no URL must red, not exit 0").toBe(1)
    expect(run.out).toContain("declares 1 candidate feed(s) but zero of them contribute a URL")
  })

  it("NC-B: NO candidateFeeds container is legitimate — exit 0, and the zero is REPORTED", async () => {
    // The floor must not fire on a manifest that simply has no feeds; that is a valid SSOT
    // state, not a defect. But the count still prints, so "observed 0 feeds" can never again
    // be indistinguishable from "observed N feeds, nothing changed".
    writeManifest({ sources: [{ hostId: "h", primarySources: [`${origin}/host`] }] })
    const run = await runCopy(["--offline"])
    expect(run.status).toBe(0)
    expect(run.out).toContain("0 candidate feed(s) → 0 URL(s)")
  })

  it("NC-C: hosts present but contributing zero URLs FAILS — the pre-existing floor still fires", async () => {
    writeManifest({ sources: [{ hostId: "h", primarySources: [] }] })
    const run = await runCopy(["--offline"])
    expect(run.status).toBe(1)
    expect(run.out).toContain("zero primarySources URLs")
  })

  it("NC-D: an empty sources array FAILS", async () => {
    writeManifest({ sources: [] })
    const run = await runCopy(["--offline"])
    expect(run.status).toBe(1)
    expect(run.out).toContain("names zero sources")
  })

  it("both kinds are counted separately, with the feed half visible", async () => {
    writeManifest(bothKinds())
    writeWatchList(null)
    const run = await runCopy(["--offline"])
    expect(run.status).toBe(0)
    expect(run.out).toContain("1 host source(s) → 1 URL(s), 1 candidate feed(s) → 1 URL(s)")
  })

  it("NC-E: a watch list present but declaring zero watches FAILS", async () => {
    // Present-but-empty is the shape that would make release-feed observation report a silent 0
    // while the job exited 0 — the same fault the candidate half shipped with.
    writeManifest(bothKinds())
    writeWatchList([])
    const run = await runCopy(["--offline"])
    expect(run.status, "an empty watch list must red, not exit 0").toBe(1)
    expect(run.out).toContain("exists but declares zero watches")
  })

  it("NC-F: a watch entry missing its url FAILS", async () => {
    writeManifest(bothKinds())
    writeWatchList([{ name: "nameless-feed" }])
    const run = await runCopy(["--offline"])
    expect(run.status).toBe(1)
    expect(run.out).toContain("missing `name` or `url`")
  })

  it("NC-G: an ABSENT watch list is legitimate — exit 0, and the zero is REPORTED", async () => {
    // Unlike the two floors above, absence is a valid state: the SSOT-backed kinds still run.
    // The count still prints, so "no list" can never read as "list with nothing new".
    writeManifest(bothKinds())
    writeWatchList(null)
    const run = await runCopy(["--offline"])
    expect(run.status).toBe(0)
    expect(run.out).toContain("watch list 0 entr(ies) → 0 URL(s)")
  })

  it("an unparseable watch list FAILS — reading its own input is this script's own job", () => {
    // The asymmetry worth preserving: an unreachable SOURCE is data (exit 0), but an unreadable
    // WATCH LIST is the script failing at its own job (exit 1). Conflating them would let a
    // corrupted list silently shrink the denominator to zero.
    const script = readFileSync(REAL_SCRIPT, "utf8")
    expect(script).toMatch(/is not parseable YAML/)
    expect(script).toMatch(/die\(`\$\{WATCH_LIST\} is not parseable YAML/)
  })
})

/*
 * ───────────────────────────────────────────────────────────────────────────────────────────
 * THE LIVE SEQUENCE — the half that had never executed.
 * ───────────────────────────────────────────────────────────────────────────────────────────
 * Four runs against loopback, in order, because each run's artifact IS the next run's
 * baseline; that chaining is the behaviour under test, not an incidental coupling. Captured
 * once in `beforeAll` so the assertions below stay independently readable and cannot silently
 * depend on vitest's within-file ordering.
 */
describe("live comparison against a baseline (loopback only, no egress)", () => {
  let first: Run
  let second: Run
  let third: Run
  let fourth: Run
  let firstArtifact: ReturnType<typeof readArtifact>

  beforeAll(async () => {
    rmSync(join(tmpRoot, "artifacts"), { recursive: true, force: true })
    served = { host: { status: 200, body: "host-v1" }, feed: { status: 200, body: "feed-v1" } }
    writeManifest(bothKinds())
    writeWatchList(null)

    first = await runCopy() // no baseline: both URLs NEW
    firstArtifact = readArtifact()

    served.feed = { status: 200, body: "feed-v2-rotated-banner" }
    second = await runCopy() // BODY change, on the candidate half

    served.feed = { status: 500, body: "feed-v2-rotated-banner" }
    third = await runCopy() // STATUS change, body held constant so the change set is exactly STATUS

    writeManifest({ sources: bothKinds().sources }) // feed removed from the SSOT
    fourth = await runCopy() // DROPPED
  }, LIVE_SEQUENCE_TIMEOUT_MS)

  it("run 1 reports an ABSENT baseline out loud, and says so unambiguously", () => {
    // A run that compared against nothing must say it. Printing this unconditionally is what
    // stops "no baseline" from reading as "no change" — the exact confusion that hid defect 2.
    expect(first.status).toBe(0)
    expect(first.out).toContain("Baseline: ABSENT")
    expect(first.out).toContain("no change can be detected this run")
    expect(first.out).toMatch(/\[NEW\] \(candidate\)/)
    expect(first.out).toMatch(/\[NEW\] \(host\)/)
  })

  it("run 1 actually FETCHED the candidate feed — 2 URLs observed, 2 reachable", () => {
    // Pre-fix this said 1. The feed was projected, schema-constrained, invariant-asserted,
    // and never opened.
    expect(first.out).toContain("Observed 2 URL(s): 2 reachable, 0 unreachable")
    expect(first.out).toContain("candidate feeds: 1 URL(s) observed, 1 reachable")
  })

  it("the artifact carries the per-URL kind and a candidate denominator", () => {
    expect(firstArtifact.counts).toMatchObject({ hostSourceUrls: 1, candidateFeedUrls: 1, candidateFeeds: 1 })
    const kinds = firstArtifact.observations.map((o: { kind: string }) => o.kind).sort()
    expect(kinds).toEqual(["CANDIDATE_FEED", "HOST_SOURCE"])
    const feed = firstArtifact.observations.find((o: { kind: string }) => o.kind === "CANDIDATE_FEED")
    expect(feed).toMatchObject({ hostId: "loopback-feed", reachable: true, status: 200 })
    expect(feed.bodySha256, "no body hash means change detection cannot work on this URL").toMatch(/^[0-9a-f]{64}$/)
  })

  it("§86: the artifact states the candidate-evidence policy, so the file cannot be read as a support claim", () => {
    // A curated third-party list saying "supports X" must never become a CallLint support
    // claim. The policy string is the thing a human reads before acting on an entry, and it
    // is asserted here so a future edit cannot quietly drop it.
    expect(firstArtifact.candidateEvidencePolicy).toMatch(/never authority/i)
    expect(firstArtifact.candidateEvidencePolicy).toMatch(/DEFERRED or DISCOVERY_ONLY/)
  })

  it("POSITIVE CONTROL: run 2 detects a candidate-feed BODY change against the restored baseline", () => {
    // The single assertion that covers both original vacuities: it requires the feed to be
    // fetched, the baseline to be read, the comparison to run, and `sourceKind` to survive
    // into the change record. Before the fix, every part of that chain was absent.
    expect(second.status).toBe(0)
    expect(second.out).toContain("Baseline: 2 URL(s) from a previous snapshot")
    expect(second.out).toMatch(/\[BODY\] \(candidate\)\s+loopback-feed/)
    expect(second.out).not.toContain("Baseline: ABSENT")
  })

  it("run 2 prints the §84 admission ceiling next to a candidate change, and never an action", () => {
    expect(second.out).toContain("generate candidate record → human approval → publish")
    expect(second.out).toContain("DEFERRED or DISCOVERY_ONLY only")
    // §19/§86: the observer reports. It must not claim to have contacted anyone.
    expect(second.out).toContain("no external PR")
    expect(second.out).not.toMatch(/submitted|opened an? (issue|pull request)|contacted/i)
  })

  it("run 2 leaves the host half alone — a feed change is not a host change", () => {
    // Conflating the two kinds is the specific way this feature turns dangerous, so the
    // isolation is asserted rather than assumed.
    expect(second.out).not.toMatch(/\[BODY\] \(host\)/)
  })

  it("run 3 detects a STATUS change and still exits 0 — a vendor 500 is data, not our failure", () => {
    expect(third.status).toBe(0)
    expect(third.out).toMatch(/\[STATUS\] \(candidate\)\s+loopback-feed\s+\S+\s+200 → 500/)
    // Body held constant across runs 2→3, so STATUS is the ONLY change. If a BODY entry
    // appeared here the hash comparison would be reacting to something other than the body.
    expect(third.out).not.toMatch(/\[BODY\]/)
    expect(third.out).toMatch(/HTTP 500\s+loopback-feed/)
  })

  it("run 4 reports a URL dropped from the SSOT, carrying the kind it had", () => {
    expect(fourth.status).toBe(0)
    expect(fourth.out).toMatch(/\[DROPPED\] \(candidate\)/)
    expect(fourth.out).toContain("no longer named in the SSOT")
  })

  it("the artifact is rewritten each run, so it is a usable baseline for the next one", () => {
    expect(existsSync(artifactPath())).toBe(true)
    const last = readArtifact()
    expect(last.counts.candidateFeedUrls, "run 4 dropped the feed").toBe(0)
    expect(last.observations).toHaveLength(1)
  })

  it("POSITIVE CONTROL: a release-feed URL is fetched and carries the third kind", async () => {
    // The same denominator pattern as the candidate half, applied to the third kind.
    rmSync(join(tmpRoot, "artifacts"), { recursive: true, force: true })
    writeManifest(bothKinds())
    writeWatchList([{ name: "loopback-release", url: `${origin}/release` }])
    served = { host: { status: 200, body: "host-v1" }, feed: { status: 200, body: "feed-v1" } }
    // Intercept /release separately so the fixture server can distinguish it from the other two.
    server.removeAllListeners("request")
    server.on("request", (req, res) => {
      const which = req.url === "/feed" ? served.feed : req.url === "/release" ? { status: 200, body: "release-v1" } : served.host
      res.writeHead(which.status, { "content-type": "text/plain" })
      res.end(which.body)
    })
    const run = await runCopy()
    expect(run.status).toBe(0)
    expect(run.out).toContain("Observed 3 URL(s): 3 reachable")
    expect(run.out).toContain("harness release feeds: 1 URL(s) observed, 1 returning 2xx")

    const artifact = readArtifact()
    expect(artifact.counts).toMatchObject({ hostSourceUrls: 1, candidateFeedUrls: 1, harnessReleaseFeedUrls: 1 })
    const kinds = artifact.observations.map((o: { kind: string }) => o.kind).sort()
    expect(kinds).toEqual(["CANDIDATE_FEED", "HARNESS_RELEASE_FEED", "HOST_SOURCE"])
    const release = artifact.observations.find((o: { kind: string }) => o.kind === "HARNESS_RELEASE_FEED")
    expect(release).toMatchObject({ hostId: "loopback-release", reachable: true, status: 200 })
    expect(release.bodySha256, "no body hash means change detection cannot work on this URL").toMatch(/^[0-9a-f]{64}$/)
  })
})

describe("the workflow restores a baseline before observing, and grants the scope to do it", () => {
  const WORKFLOW = resolve(ROOT, ".github", "workflows", "distribution-watch.yml")
  const yml = readFileSync(WORKFLOW, "utf8")

  it("a restore step exists and resolves a PREVIOUS run, not the current one", () => {
    // `actions/download-artifact` defaults to `run-id: ${{ github.run_id }}` — the current
    // run, which has uploaded nothing at that point. A name-only download would fetch nothing
    // and, because the step must tolerate a legitimately absent baseline, fail quietly and
    // reproduce the exact vacuity it was added to remove. So the resolution is explicit.
    expect(yml).toMatch(/name: Restore previous official-source observation/)
    expect(yml).toMatch(/actions\/artifacts\?name=/)
    expect(yml).toMatch(/gh run download/)
    expect(yml).toMatch(/workflow_run\.id/)
  })

  it("the restore is ordered BEFORE the observation, which is before the upload", () => {
    const restore = yml.indexOf("name: Restore previous official-source observation")
    const observe = yml.indexOf("name: Observe vendor sources, candidate feeds and harness release feeds")
    const upload = yml.indexOf("name: Upload official-source observation")
    expect(restore).toBeGreaterThan(-1)
    expect(observe).toBeGreaterThan(restore)
    expect(upload).toBeGreaterThan(observe)
  })

  it("`actions: read` is granted — `contents: read` alone cannot list a sibling run's artifacts", () => {
    expect(yml).toMatch(/permissions:[\s\S]*?actions: read/)
  })

  it("the artifact list is explicitly ordered — the repo-level API documents no sort order", () => {
    expect(yml).toMatch(/sort_by\(\.created_at\)/)
    expect(yml).toMatch(/select\(\.expired == false\)/)
  })

  it("the projection check is the generator's own --check, not a hand-listed path set", () => {
    // A hand-maintained mirror of a generator's write set goes stale in the safe-looking
    // direction: `git diff` on an untouched path always exits 0. This one measured 9 of 29.
    expect(yml).toMatch(/generate-distribution-surfaces\.mjs --check/)
  })
})
