#!/usr/bin/env tsx
/**
 * Gate B / PR-D3 — human-calibration gate report generator (new12 §2.6/§6.1; ADR
 * 0053 §4 `REVIEW_HOLD`).
 *
 * Projects the negative-verdict baked Trust Pages (BLOCK + high-sev REVIEW) into a
 * committed, human-readable calibration report, pairing each negative artifact with
 * the human sign-offs recorded in the committed review store
 * (`packages/trust-index/calibration/review-store.json`). It computes NOTHING new —
 * `runCalibrationAudit()` re-bakes the SAME cohort through the SAME engines and reads
 * verdicts/findings VERBATIM. This script only renders that report deterministically.
 *
 * It NEVER writes a reviewer sign-off. Sign-offs are DATA a human appends to the
 * review store and commits; only then can the gate pass (ADR 0053 §4: dual human
 * review is the `REVIEW_HOLD` exit condition). The report is an OFFLINE audit
 * artifact (`packages/trust-index/calibration/`), never a public Trust Page (§6).
 *
 * Modes:
 *   (default) --check : committed report must be byte-identical to a fresh render.
 *                       Exit 1 on drift. Exit 0 on match REGARDLESS of gate pass/fail
 *                       — so CI stays green while the gate status is honestly recorded
 *                       in the artifact (a pending gate is the correct state, not a
 *                       build break).
 *   --write           : (re)generate the committed .json + .md. Exit 0.
 *   --gate            : the ENFORCEMENT mode. Exit 2 when Gate-B thresholds are not
 *                       met (i.e. sign-offs pending / precision below floor / any
 *                       false-SAFE). This is the mode a negative-page PUBLISH step
 *                       must call before serving a new negative page.
 *
 * Exit codes: 0 ok · 1 drift (--check) · 2 gate not passed (--gate) or unexpected error.
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import {
  runCalibrationAudit,
  EMPTY_REVIEW_STORE,
  type CalibrationReport,
  type ReviewStore,
} from "../packages/trust-index/src/calibration.js"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, "..")
const calDir = path.join(repoRoot, "packages", "trust-index", "calibration")
const storePath = path.join(calDir, "review-store.json")
const jsonPath = path.join(calDir, "calibration.json")
const mdPath = path.join(calDir, "calibration.md")

const pct = (n: number | null) => (n === null ? "n/a" : `${(n * 100).toFixed(1)}%`)

/** Load the committed review store, or the empty store if none exists yet. */
function loadReviewStore(): ReviewStore {
  if (!fs.existsSync(storePath)) return EMPTY_REVIEW_STORE
  const parsed = JSON.parse(fs.readFileSync(storePath, "utf8")) as ReviewStore
  if (parsed.schema !== "calllint.calibration-review.v0") {
    throw new Error(`review store has unexpected schema: ${String(parsed.schema)}`)
  }
  return { schema: parsed.schema, signoffs: parsed.signoffs ?? {} }
}

/** Render the deterministic Markdown report from the structured audit. */
function renderMarkdown(r: CalibrationReport): string {
  const m = r.measures
  const gateLine = r.pass
    ? "**Gate B: ✅ PASSED** — every negative artifact is dual-reviewed and thresholds are met."
    : `**Gate B: ⛔ NOT PASSED** — ${r.blockedReasons.join(" ")} No new negative page may publish until this passes (ADR 0053 §4 \`REVIEW_HOLD\`).`

  const negRows = r.negatives
    .map((n) => {
      const findings = n.findings.map((f) => `${f.id} (${f.severity})`).join("; ") || "—"
      const reviewers =
        n.signoffs.length === 0
          ? "⏳ pending"
          : n.signoffs.map((s) => `${s.reviewer}:${s.decision}`).join(", ")
      const dual = n.dualReviewed ? "✅" : "🔴"
      const fsafe = n.falseSafe ? "⛔ FALSE-SAFE" : "ok"
      return `| \`${n.canonicalName}\` | ${n.verdict} | ${findings} | ${n.completeness} | ${dual} ${reviewers} | ${fsafe} |`
    })
    .join("\n")

  return `# CallLint Human-Calibration Gate (Gate B / PR-D3)

> Generated by \`pnpm audit:calibration:write\` from the negative-verdict baked pages
> (BLOCK + high-severity REVIEW). Regenerate with the same command; CI runs \`--check\`
> and fails only on DRIFT. This is an **offline audit artifact**
> (\`packages/trust-index/calibration/\`), never a public Trust Page (ADR 0053 §6).
>
> This file is the **gate**, not the review. Reviewer sign-offs are DATA a human
> appends to \`review-store.json\` and commits; only then can the gate pass. The agent
> builds the gate and NEVER signs off (ADR 0053 §4: dual human review is the
> \`REVIEW_HOLD\` exit condition; a claim/render never moves a verdict).

${gateLine}

## Aggregate measures

| measure | value | threshold |
|---|---|---|
| Negative artifacts (BLOCK + high-sev REVIEW) | ${m.negativeCount} | — |
| BLOCK artifacts | ${m.blockerCount} | — |
| Dual-reviewed (≥${r.thresholds.reviewersPerArtifact} distinct reviewers) | ${m.dualReviewedCount} / ${m.negativeCount} | = ${m.negativeCount} |
| Dangerous false-SAFE | ${m.falseSafeCount} | = ${r.thresholds.falseSafe} |
| Blocker precision (over reviewed BLOCKs) | ${pct(m.blockerPrecision)} | ≥ ${(r.thresholds.blockerPrecision * 100).toFixed(0)}% |
| Byte-reproducible projection | ${r.deterministic ? "yes" : "NO"} | = yes |

## Negative artifacts awaiting / carrying calibration

| artifact | verdict | findings | completeness | reviewers | false-SAFE |
|---|---|---|---|---|---|
${negRows}

## How to record a sign-off (human only)

Append to \`packages/trust-index/calibration/review-store.json\` under the artifact's
\`artifactDigest\`, then run \`pnpm audit:calibration:write\` and commit:

\`\`\`json
{
  "schema": "calllint.calibration-review.v0",
  "signoffs": {
    "sha256:<artifactDigest>": [
      { "reviewer": "<handle>", "decision": "confirmed", "at": "<ISO-8601 UTC>", "note": "<why>" }
    ]
  }
}
\`\`\`

\`decision\` is the reviewer's own judgment of whether the negative conclusion is a true
positive; it is NEVER a re-scored verdict and can never move the page's verdict.
`
}

function main(): void {
  const argv = process.argv.slice(2)
  const mode = argv.includes("--write")
    ? "write"
    : argv.includes("--gate")
      ? "gate"
      : "check"

  const store = loadReviewStore()
  const report = runCalibrationAudit(store)

  const json = JSON.stringify(report, null, 2) + "\n"
  const md = renderMarkdown(report)

  if (mode === "write") {
    fs.mkdirSync(calDir, { recursive: true })
    // Seed an empty review store on first write so the human has a file to edit.
    if (!fs.existsSync(storePath)) {
      fs.writeFileSync(storePath, JSON.stringify(EMPTY_REVIEW_STORE, null, 2) + "\n")
    }
    fs.writeFileSync(jsonPath, json)
    fs.writeFileSync(mdPath, md)
    console.log(
      `calibration-audit: wrote ${path.relative(repoRoot, jsonPath)} + .md ` +
        `(Gate B ${report.pass ? "PASSED" : "NOT PASSED"}: ${report.measures.dualReviewedCount}/${report.measures.negativeCount} dual-reviewed).`,
    )
    return
  }

  if (mode === "gate") {
    if (report.pass) {
      console.log(
        `calibration-audit: Gate B PASSED — ${report.measures.negativeCount} negative artifacts dual-reviewed, ` +
          `blocker precision ${pct(report.measures.blockerPrecision)}, 0 false-SAFE.`,
      )
      return
    }
    console.error("calibration-audit: Gate B NOT PASSED — negative publishing is blocked (ADR 0053 §4).")
    for (const reason of report.blockedReasons) console.error(`  - ${reason}`)
    console.error("Record dual human sign-offs in review-store.json, then re-run.")
    process.exit(2)
  }

  // --check (CI default): drift only. A pending gate is the correct state, not a break.
  const drift: string[] = []
  for (const [p, want] of [[jsonPath, json], [mdPath, md]] as const) {
    const have = fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null
    if (have !== want) drift.push(path.relative(repoRoot, p))
  }
  if (drift.length > 0) {
    console.error(`calibration-audit: committed report is STALE: ${drift.join(", ")}`)
    console.error("Run `pnpm audit:calibration:write` and commit the result.")
    process.exit(1)
  }
  console.log(
    `calibration-audit: committed report matches ` +
      `(Gate B ${report.pass ? "PASSED" : "NOT PASSED"}; ${report.measures.dualReviewedCount}/${report.measures.negativeCount} dual-reviewed). ` +
      `Run \`pnpm audit:calibration --gate\` to enforce before publishing a negative page.`,
  )
}

try {
  main()
} catch (err) {
  console.error("calibration-audit: unexpected error", err)
  process.exit(2)
}
