#!/usr/bin/env tsx
/**
 * Gate A / PR-D1 — coverage & precision audit report generator (new12 §6; ADR 0053).
 *
 * Projects the shipped 100-object benchmark into a committed, human-readable audit
 * report. It computes NOTHING new — `runCoverageAudit()` runs the SAME corpus through
 * the SAME real resolvers and rolls the outcome up. This script only renders that
 * report deterministically and either VERIFIES the committed copies match (`--check`,
 * the CI default) or REWRITES them (`--write`).
 *
 * The report is an OFFLINE audit artifact (packages/resolver/audit/), never a public
 * Trust Page (ADR 0053 §6: no public scale-up at Gate A).
 *
 * Exit codes: 0 match/written · 1 drift (in --check) · 2 threshold failure.
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { runCoverageAudit, type CoverageAuditReport } from "../packages/resolver/test/evidence/coverageAudit.js"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, "..")
const auditDir = path.join(repoRoot, "packages", "resolver", "audit")
const jsonPath = path.join(auditDir, "coverage-audit.json")
const mdPath = path.join(auditDir, "coverage-audit.md")

const pct = (n: number) => `${(n * 100).toFixed(1)}%`

/** Render the deterministic Markdown report from the structured audit. */
function renderMarkdown(r: CoverageAuditReport): string {
  const t = r.thresholds
  const rateRow = (label: string, value: string, threshold: string, ok: boolean) =>
    `| ${label} | ${value} | ${threshold} | ${ok ? "✅" : "❌"} |`
  const rates = [
    rateRow("Identity resolution", pct(r.rates.identityRate), `≥ ${pct(t.identity)}`, r.rates.identityRate >= t.identity),
    rateRow("Repo mapping", `${pct(r.rates.repoRate)} (n=${r.rates.repoDenominator})`, `≥ ${pct(t.repo)}`, r.rates.repoRate >= t.repo),
    rateRow("Evidence completeness", pct(r.rates.completenessRate), `≥ ${pct(t.completeness)}`, r.rates.completenessRate >= t.completeness),
    rateRow("Dangerous false-SAFE", String(r.rates.falseSafeCount), `= ${t.falseSafe}`, r.rates.falseSafeCount === t.falseSafe),
    rateRow("Determinism (repeat pass)", r.deterministic ? "byte-identical" : "DIVERGED", "= identical", r.deterministic),
  ].join("\n")

  const groupTable = (title: string, rows: CoverageAuditReport["bySubjectType"]) =>
    `### ${title}\n\n| group | total | clean | resolvable | malicious | conflict |\n|---|--:|--:|--:|--:|--:|\n` +
    rows.map((g) => `| \`${g.key}\` | ${g.total} | ${g.clean} | ${g.resolvable} | ${g.malicious} | ${g.conflict} |`).join("\n")

  const matrix = r.coverageMatrix
    .map((c) => `| \`${c.klass}\` | ${c.covered ? "✅ covered" : "◇ not yet"} | ${c.objectCount} | ${c.note} |`)
    .join("\n")

  return `# CallLint Coverage & Precision Audit (Gate A / PR-D1)

> Generated by \`pnpm audit:coverage --write\` from the shipped 100-object benchmark
> (\`packages/resolver/test/evidence/corpus.ts\`). Regenerate with the same command;
> CI runs \`--check\` and fails on drift. This is an **offline audit artifact**, never
> a public Trust Page (ADR 0053 §6). It measures **evidence/identity coverage**; the
> operation-class precision (read/write/message/financial/gateway) is measured by the
> authority corpus + bench gates (\`pnpm corpus:test\` / \`pnpm bench:test\`).

**Objects audited:** ${r.objectCount} · **Gate A pass:** ${r.pass ? "✅ YES" : "❌ NO"}

## §P1 acceptance rates (resolvable, non-conflict, non-malicious sample; n=${r.rates.sampleSize})

| measure | observed | threshold | ok |
|---|---|---|:--:|
${rates}

## Honest coverage matrix

Six subject types are covered end-to-end by shipped resolvers. Four registry/transport
classes are **stated as not-yet-covered** — such subjects resolve UNKNOWN, never SAFE
(UNKNOWN honesty; ADR 0053 §1 \`I-04\`). Coverage grows only under the feasibility gate.

| class | coverage | corpus objects | note |
|---|---|--:|---|
${matrix}

**Not yet covered:** ${r.uncoveredClasses.map((c) => `\`${c}\``).join(", ")}.

${groupTable("Rollup by subject type", r.bySubjectType)}

${groupTable("Rollup by category", r.byCategory)}
`
}

async function main(): Promise<void> {
  const mode = process.argv.includes("--write") ? "write" : "check"
  const report = await runCoverageAudit()

  if (!report.pass) {
    console.error("coverage-audit: Gate-A thresholds NOT met — refusing to proceed.")
    console.error(JSON.stringify(report.rates, null, 2))
    process.exit(2)
  }

  const json = JSON.stringify(report, null, 2) + "\n"
  const md = renderMarkdown(report)

  if (mode === "write") {
    fs.mkdirSync(auditDir, { recursive: true })
    fs.writeFileSync(jsonPath, json)
    fs.writeFileSync(mdPath, md)
    console.log(`coverage-audit: wrote ${path.relative(repoRoot, jsonPath)} + .md (Gate A pass).`)
    return
  }

  const drift: string[] = []
  for (const [p, want] of [[jsonPath, json], [mdPath, md]] as const) {
    const have = fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null
    if (have !== want) drift.push(path.relative(repoRoot, p))
  }
  if (drift.length > 0) {
    console.error(`coverage-audit: committed report is STALE: ${drift.join(", ")}`)
    console.error("Run `pnpm audit:coverage --write` and commit the result.")
    process.exit(1)
  }
  console.log(`coverage-audit: committed report matches (Gate A pass, ${report.objectCount} objects).`)
}

main().catch((err) => {
  console.error("coverage-audit: unexpected error", err)
  process.exit(2)
})
